image: python:latest

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

stages:
  - test

test:
  stage: test
  before_script:
    - pip install --no-cache-dir --requirement requirements.txt
  script:
    - FLASK_ENV=testing PYTHONPATH=${PWD} pytest --cov=${PWD}
  coverage: '/TOTAL.*\s+(\d+%)$/'
