image: python:latest

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

stages:
  - test

test:
  stage: test
  before_script:
    - pip install --no-cache-dir --requirement requirements.txt
  script:
    - FLASK_ENV=testing pytest --junitxml=pytest.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      junit: pytest.xml

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
